### ISSUE TITLE
Can you produce a GeoJSON file for each and generate a metadata entry for each?

### ISSUE THREAD

**Issue by JJediny** [nationalparkservice/nps-gtfs#1]
Good afternoon,
 
In cooperation with the National Parks Service, the U.S. Department of Transportation Volpe Center has been working on a pilot project to digitize NPS transit systems’ schedules in GTFS format. Presently the pilot program includes the Boston Harbor Islands ferries, shuttles at Rocky Mountain National Park, and the train at Cuyahoga Valley National Park.
 
We are reaching out to data aggregators and indices in order to promote access to the newly-developed NPS GTFS feeds. Inclusion of these feeds in your service will help developers learn about and access the data, thereby encouraging app development that will help the general public access national parks. The data is available openly on the NPS GTFS GitHub, located at https://github.com/nationalparkservice/nps-gtfs.
 
Please let us know if you have questions about the data, if there are steps we can take to help you use this data in your service, or if you would like to further discuss the project. Thanks!
 
E B

**Comment by drewda** [comment]
FYI, all of the feeds included in this repository are also aggregated and available through the Transitland open transit data platform:

- Boston Harbor Islands National and State Park: https://transit.land/feed-registry/operators/o-drt8-bostonharborislandsnationalandstatepark

- Cuyahoga Valley Scenic Railroad: https://transit.land/feed-registry/operators/o-dpmf-cuyahogavalleyscenicrailroad

- Yosemite Valley Shuttle System: https://transit.land/feed-registry/operators/o-9qdyw-yosemitevalleyshuttlesystem

- Yosemite Area Regional Transportation System (YARTS): https://transit.land/feed-registry/operators/o-9qd-yosemitearearegionaltransportationsystem

- Rocky Mountain National Park Shuttles: https://transit.land/feed-registry/operators/o-9xhv-rockymountainnationalpark

- Town of Estes Park (Estes Park Free Shuttles): https://transit.land/feed-registry/operators/o-9xhvw-townofestespark

From the Transitland Feed Registry pages linked above, you can follow links to view GeoJSON for each agency/operator service area, stop locations, route lines, etc.

This data is also available for querying through the Transitland Datastore API: https://transit.land/documentation/datastore/api-endpoints.html
